#!/bin/bash
# 部署命令脚本

echo "=========================================="
echo "智能作业管理系统 - GitHub 部署命令"
echo "=========================================="
echo ""
echo "请先在 GitHub 创建仓库: https://github.com/new"
echo "仓库名: homework-system"
echo ""
echo "创建完成后，执行以下命令:"
echo ""
echo "# 添加远程仓库"
echo "git remote add origin https://github.com/steel123456/homework-system.git"
echo ""
echo "# 推送代码到 GitHub"
echo "git push -u origin main"
echo ""
echo "=========================================="
echo "如果需要 Personal Access Token:"
echo "1. 访问: https://github.com/settings/tokens"
echo "2. Generate new token (classic)"
echo "3. 勾选 repo 权限"
echo "4. 复制生成的 token (ghp_开头)"
echo "=========================================="
